
import React from 'react';
import { XIcon, SparklesIcon } from './icons';

interface AISummaryModalProps {
  isOpen: boolean;
  onClose: () => void;
  summary: string;
  isLoading: boolean;
}

const AISummaryModal: React.FC<AISummaryModalProps> = ({ isOpen, onClose, summary, isLoading }) => {
  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 bg-black bg-opacity-60 z-50 flex justify-center items-center p-4" onClick={onClose}>
      <div 
        className="bg-white rounded-2xl shadow-2xl w-full max-w-2xl transform transition-all duration-300 scale-95 opacity-0 animate-fade-in-scale" 
        onClick={(e) => e.stopPropagation()}
        style={{ animation: 'fade-in-scale 0.3s ease-out forwards' }}
      >
        <div className="p-6 border-b border-gray-200 flex justify-between items-center">
          <div className="flex items-center space-x-3">
            <SparklesIcon className="h-7 w-7 text-primary" />
            <h2 className="text-xl font-bold text-primary">AI-Powered Anomaly Summary</h2>
          </div>
          <button onClick={onClose} className="p-2 rounded-full text-secondary hover:bg-gray-100">
            <XIcon className="h-6 w-6" />
          </button>
        </div>
        <div className="p-8">
          {isLoading ? (
            <div className="flex flex-col items-center justify-center h-48">
              <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary"></div>
              <p className="mt-4 text-secondary">Generating insights with Gemini...</p>
            </div>
          ) : (
            <div className="prose prose-sm max-w-none text-secondary whitespace-pre-wrap font-sans">
                {summary}
            </div>
          )}
        </div>
        <div className="px-6 py-4 bg-light-bg rounded-b-2xl text-xs text-gray-500 text-center">
            Summary generated by Gemini. Please verify all critical information.
        </div>
      </div>
      <style>{`
        @keyframes fade-in-scale {
          from { transform: scale(0.95); opacity: 0; }
          to { transform: scale(1); opacity: 1; }
        }
        .animate-fade-in-scale {
            animation: fade-in-scale 0.3s ease-out forwards;
        }
      `}</style>
    </div>
  );
};

export default AISummaryModal;
